print('Hello, World!')
print('preciso de ajuda')
print('preciso dormir')
print('preciso comer')
print('estou com fome')
print('quero minha casa')
print('volte a sonhar')
print('quero ser rico')
print('estou duro e devendo')
print('Sou muito lindo')